[versions]
ucanaccess = "[5.0.1,6)"
junit-jupiter = "[5.11,6)"
junit-platform = "[1.11,2)"
mockito = "[5.14,6)"

[libraries]
ucanaccess = { group = "net.sf.ucanaccess", name = "ucanaccess", version.ref = "ucanaccess" }

junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }

mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }

[bundles]
junit = [
    "junit-api",
    "junit-engine",
    "junit-platform"
]
testLibraries = [
    "junit-api",
    "junit-engine",
    "junit-platform",
    "mockito"
]
