#include "etcs-common.h"

/**
 * This must be kept in sync with the field initialization below.
 */
typedef enum {
        VAR_A_NVMAXREDADH1,
        VAR_A_NVMAXREDADH2,
        VAR_A_NVMAXREDADH3,
        VAR_A_NVP12,
        VAR_A_NVP23,
        VAR_D_ADHESION,
        VAR_D_AXLELOAD,
        VAR_D_CURRENT,
        VAR_D_CYCLOC,
        VAR_D_DP,
        VAR_D_EMERGENCYSTOP,
        VAR_D_ENDTIMERSTARTLOC,
        VAR_D_GRADIENT,
        VAR_D_INFILL,
        VAR_D_LEVELTR,
        VAR_D_LINK,
        VAR_D_LOC,
        VAR_D_LOOP,
        VAR_D_LRBG,
        VAR_D_LX,
        VAR_D_MAMODE,
        VAR_D_NVOVTRP,
        VAR_D_NVPOTRP,
        VAR_D_NVROLL,
        VAR_D_NVSTFF,
        VAR_D_OL,
        VAR_D_PBD,
        VAR_D_PBDSR,
        VAR_D_POSOFF,
        VAR_D_RBCTR,
        VAR_D_REF,
        VAR_D_REVERSE,
        VAR_D_SECTIONTIMERSTOPLOC,
        VAR_D_SR,
        VAR_D_STARTOL,
        VAR_D_STARTREVERSE,
        VAR_D_STATIC,
        VAR_D_SUITABILITY,
        VAR_D_TAFDISPLAY,
        VAR_D_TEXTDISPLAY,
        VAR_D_TRACKINIT,
        VAR_D_TRACKCOND,
        VAR_D_TRACTION,
        VAR_D_TSR,
        VAR_D_VALIDNV,
        VAR_G_A,
        VAR_G_PBDSR,
        VAR_G_TSR,
        VAR_L_ACKLEVELTR,
        VAR_L_ACKMAMODE,
        VAR_L_ADHESION,
        VAR_L_AXLELOAD,
        VAR_L_CONSISTFRONTENGINEMAX,
        VAR_L_CONSISTFRONTENGINEMIN,
        VAR_L_CONSISTFRONTENGINENOM,
        VAR_L_CONSISTREARENGINEMAX,
        VAR_L_CONSISTREARENGINEMIN,
        VAR_L_CONSISTREARENGINENOM,
        VAR_L_DOUBTOVER,
        VAR_L_DOUBTUNDER,
        VAR_L_ENDSECTION,
        VAR_L_LOOP,
        VAR_L_LX,
        VAR_L_MAMODE,
        VAR_L_MESSAGE,
        VAR_L_NVKRINT,
        VAR_L_PACKET,
        VAR_L_PBDSR,
        VAR_L_REVERSEAREA,
        VAR_L_SECTION,
        VAR_L_STOPLX,
        VAR_L_TAFDISPLAY,
        VAR_L_TEXT,
        VAR_L_TEXTDISPLAY,
        VAR_L_TRACKCOND,
        VAR_L_TRAIN,
        VAR_L_TRAININT,
        VAR_L_TSR,
        VAR_M_ACK,
        VAR_M_ADHESION,
        VAR_M_AIRTIGHT,
        VAR_M_AXLELOADCAT,
        VAR_M_CURRENT,
        VAR_M_DUP,
        VAR_M_ERROR,
        VAR_M_LEVEL,
        VAR_M_LEVELTEXTDISPLAY,
        VAR_M_LEVELTR,
        VAR_M_LINEGAUGE,
        VAR_M_LINEAXLELOADCAT,
        VAR_M_LOADINGGAUGE,
        VAR_M_LOC,
        VAR_M_MAMODE,
        VAR_M_MCOUNT,
        VAR_M_MODE,
        VAR_M_MODE_V1, // v1 + v2
        VAR_M_MODETEXTDISPLAY,
        VAR_M_NVAVADH,
        VAR_M_NVCONTACT,
        VAR_M_NVDERUN,
        VAR_M_NVEBCL,
        VAR_M_NVKRINT,
        VAR_M_NVKTINT,
        VAR_M_NVKVINT,
        VAR_M_PLATFORM,
        VAR_M_POSITION,
        VAR_M_POSITION_V1, // v1
        VAR_M_TRACKCOND,
        VAR_M_VOLTAGE,
        VAR_M_VERSION,
        VAR_N_AXLE,
        VAR_N_ITER,
        VAR_N_PIG,
        VAR_N_TOTAL,
        VAR_NC_CDDIFF,
        VAR_NC_CDTRAIN,
        VAR_NC_DIFF,
        VAR_NC_TRAIN,
        VAR_NID_BG,
        VAR_NID_C,
        VAR_NID_CTRACTION,
        VAR_NID_EM,
        VAR_NID_ENGINE,
        VAR_NID_LOOP,
        VAR_NID_LRBG,
        VAR_NID_LTRBG,
        VAR_NID_LX,
        VAR_NID_MESSAGE,
        VAR_NID_MN,
        VAR_NID_OPERATIONAL,
        VAR_NID_PACKET,
        VAR_NID_PRVLRBG,
        VAR_NID_RADIO,
        VAR_NID_RBC,
        VAR_NID_RIU,
        VAR_NID_NTC,
        VAR_NID_TEXTMESSAGE,
        VAR_NID_TSR,
        VAR_NID_VBCMK,
        VAR_NID_XUSER,
        VAR_Q_ASPECT,
        VAR_Q_CONFTEXTDISPLAY,
        VAR_Q_DANGERPOINT,
        VAR_Q_DIFF,
        VAR_Q_DESK,
        VAR_Q_DIR,
        VAR_Q_DIRLRBG,
        VAR_Q_DIRTRAIN,
        VAR_Q_DLRBG,
        VAR_Q_EMERGENCYSTOP,
        VAR_Q_ENDTIMER,
        VAR_Q_FRONT,
        VAR_Q_GDIR,
        VAR_Q_INFILL,
        VAR_Q_INTEGRITY,
        VAR_Q_SAFECONSISTLENGTH,
        VAR_Q_LGTLOC,
        VAR_Q_LINK,
        VAR_Q_LOCACC,
        VAR_Q_LINKORIENTATION,
        VAR_Q_LINKREACTION,
        VAR_Q_LOOPDIR,
        VAR_Q_LSSMA,
        VAR_Q_LXSTATUS,
        VAR_Q_MAMODE,
        VAR_Q_MARQSTREASON,
        VAR_Q_MEDIA,
        VAR_Q_MPOSITION,
        VAR_Q_NETWORKTYPE,
        VAR_Q_NEWCOUNTRY,
        VAR_Q_NVDRIVER_ADHES,
        VAR_Q_NVEMRRLS,
        VAR_Q_NVGUIPERM,
        VAR_Q_NVINHSMICPERM,
        VAR_Q_NVKINT,
        VAR_Q_NVKVINTSET,
        VAR_Q_NVLOCACC,
        VAR_Q_NVSBFBPERM,
        VAR_Q_NVSBTSMPERM,
        VAR_Q_ORIENTATION,
        VAR_Q_OVERLAP,
        VAR_Q_PBDSR,
        VAR_Q_PLATFORM,
        VAR_Q_RBC,
        VAR_Q_RIU,
        VAR_Q_SCALE,
        VAR_Q_SECTIONTIMER,
        VAR_Q_SLEEPSESSION,
        VAR_Q_SRSTOP,
        VAR_Q_SSCODE,
        VAR_Q_STATUSLRBG,
        VAR_Q_STOPLX,
        VAR_Q_SUITABILITY,
        VAR_Q_TEXT,
        VAR_Q_TEXTCLASS,
        VAR_Q_TEXTCONFIRM,
        VAR_Q_TEXTDISPLAY,
        VAR_Q_TEXTREPORT,
        VAR_Q_TRACKINIT,
        VAR_Q_UPDOWN,
        VAR_Q_VBCO,
        VAR_T_CYCLOC,
        VAR_T_CYCRQST,
        VAR_T_LSSMA,
        VAR_T_ENDTIMER,
        VAR_T_EMA,
        VAR_T_MAR,
        VAR_T_NVCONTACT,
        VAR_T_NVOVTRP,
        VAR_T_OL,
        VAR_T_SECTIONTIMER,
        VAR_T_TEXTDISPLAY,
        VAR_T_TIMEOUTRQST,
        VAR_T_TRAIN,
        VAR_T_VBC,
        VAR_V_AXLELOAD,
        VAR_V_DIFF,
        VAR_V_EMA,
        VAR_V_LX,
        VAR_V_MAIN,
        VAR_V_MAMODE,
        VAR_V_MAXTRAIN,
        VAR_V_NVALLOWOVTRP,
        VAR_V_NVKVINT,
        VAR_V_NVLIMSUPERV,
        VAR_V_NVONSIGHT,
        VAR_V_NVSUPOVTRP,
        VAR_V_NVREL,
        VAR_V_NVSHUNT,
        VAR_V_NVSTFF,
        VAR_V_NVUNFIT,
        VAR_V_RELEASEDP,
        VAR_V_RELEASEOL,
        VAR_V_REVERSE,
        VAR_V_SM,
        VAR_V_STATIC,
        VAR_V_TRAIN,
        VAR_V_TSR,
        VAR_X_TEXT,
        VAR_M_AXLELOAD_V1, // v1
        VAR_M_TRACKCONDBC_V1, // v1
        VAR_M_TRACTION_V1, // v1
        VAR_Q_TRACKDEL_V1, // v1
} variable_type;

#define DEF_VAR(name, size) { name , ( size ), 0, "etcs.var." name, NULL, NULL, NULL }

#define DEF_VAR_CUSTOM(name, size, registrator, dissect, dissect_ret) { name , ( size ), 0, "etcs.var." name, registrator, dissect, dissect_ret }

static proto_item *dissect_var_ret_x_text(const etcs_variable_t self, tvbuff_t *tvb, proto_tree *tree, unsigned *offset,
                                          uint64_t *return_value) {
        proto_item *item = proto_tree_add_bits_ret_val(
                tree,
                self.wireshark_hf,
                tvb,
                *offset,
                self.size,
                return_value,
                ENC_BIG_ENDIAN
        );
        *offset += self.size;
        const uint64_t value = *return_value;
        const char c = (char) value;
        // display printable ASCII characters; pad so that it lines up after decimal value
        if (value >= ' ' && value <= 99) {
                proto_item_append_text(item, "  ['%c']", c);
        } else if (value >= 100 && value <= '~') {
                proto_item_append_text(item, " ['%c']", c);
        }
        return item;
}

static proto_item *dissect_var_ret_m_version(const etcs_variable_t self, tvbuff_t *tvb, proto_tree *tree,
                                             unsigned *offset, uint64_t *return_value) {
        proto_item *item = proto_tree_add_bits_ret_val(
                tree,
                self.wireshark_hf,
                tvb,
                *offset,
                self.size,
                return_value,
                ENC_BIG_ENDIAN
        );
        const etcs_version_t version = read_etcs_version(tvb, *offset);
        *offset += self.size;
        proto_item_append_text(item, " [\"%" PRIu8 ".%" PRIu8 "\"]", version.major, version.minor);
        return item;
}

/**
 * This must be kept in sync with the enumeration above.
 */
static etcs_variable_t etcs_variables[] = {
        DEF_VAR("A_NVMAXREDADH1", 6),
        DEF_VAR("A_NVMAXREDADH2", 6),
        DEF_VAR("A_NVMAXREDADH3", 6),
        DEF_VAR("A_NVP12", 6),
        DEF_VAR("A_NVP23", 6),
        DEF_VAR("D_ADHESION", 15),
        DEF_VAR("D_AXLELOAD", 15),
        DEF_VAR("D_CURRENT", 15),
        DEF_VAR("D_CYCLOC", 15),
        DEF_VAR("D_DP", 15),
        DEF_VAR("D_EMERGENCYSTOP", 15),
        DEF_VAR("D_ENDTIMERSTARTLOC", 15),
        DEF_VAR("D_GRADIENT", 15),
        DEF_VAR("D_INFILL", 15),
        DEF_VAR("D_LEVELTR", 15),
        DEF_VAR("D_LINK", 15),
        DEF_VAR("D_LOC", 15),
        DEF_VAR("D_LOOP", 15),
        DEF_VAR("D_LRBG", 15),
        DEF_VAR("D_LX", 15),
        DEF_VAR("D_MAMODE", 15),
        DEF_VAR("D_NVOVTRP", 15),
        DEF_VAR("D_NVPOTRP", 15),
        DEF_VAR("D_NVROLL", 15),
        DEF_VAR("D_NVSTFF", 15),
        DEF_VAR("D_OL", 15),
        DEF_VAR("D_PBD", 15),
        DEF_VAR("D_PBDSR", 15),
        DEF_VAR("D_POSOFF", 15),
        DEF_VAR("D_RBCTR", 15),
        DEF_VAR("D_REF", 16),
        DEF_VAR("D_REVERSE", 15),
        DEF_VAR("D_SECTIONTIMERSTOPLOC", 15),
        DEF_VAR("D_SR", 15),
        DEF_VAR("D_STARTOL", 15),
        DEF_VAR("D_STARTREVERSE", 15),
        DEF_VAR("D_STATIC", 15),
        DEF_VAR("D_SUITABILITY", 15),
        DEF_VAR("D_TAFDISPLAY", 15),
        DEF_VAR("D_TEXTDISPLAY", 15),
        DEF_VAR("D_TRACKINIT", 15),
        DEF_VAR("D_TRACKCOND", 15),
        DEF_VAR("D_TRACTION", 15),
        DEF_VAR("D_TSR", 15),
        DEF_VAR("D_VALIDNV", 15),
        DEF_VAR("G_A", 8),
        DEF_VAR("G_PBDSR", 8),
        DEF_VAR("G_TSR", 8),
        DEF_VAR("L_ACKLEVELTR", 15),
        DEF_VAR("L_ACKMAMODE", 15),
        DEF_VAR("L_ADHESION", 15),
        DEF_VAR("L_AXLELOAD", 15),
        DEF_VAR("L_CONSISTFRONTENGINEMAX", 15),
        DEF_VAR("L_CONSISTFRONTENGINEMIN", 12),
        DEF_VAR("L_CONSISTFRONTENGINENOM", 12),
        DEF_VAR("L_CONSISTREARENGINEMAX", 12),
        DEF_VAR("L_CONSISTREARENGINEMIN", 12),
        DEF_VAR("L_CONSISTREARENGINENOM", 12),
        DEF_VAR("L_DOUBTOVER", 15),
        DEF_VAR("L_DOUBTUNDER", 15),
        DEF_VAR("L_ENDSECTION", 15),
        DEF_VAR("L_LOOP", 15),
        DEF_VAR("L_LX", 15),
        DEF_VAR("L_MAMODE", 15),
        DEF_VAR("L_MESSAGE", 10),
        DEF_VAR("L_NVKRINT", 5),
        DEF_VAR("L_PACKET", 13),
        DEF_VAR("L_PBDSR", 15),
        DEF_VAR("L_REVERSEAREA", 15),
        DEF_VAR("L_SECTION", 15),
        DEF_VAR("L_STOPLX", 15),
        DEF_VAR("L_TAFDISPLAY", 15),
        DEF_VAR("L_TEXT", 8),
        DEF_VAR("L_TEXTDISPLAY", 15),
        DEF_VAR("L_TRACKCOND", 15),
        DEF_VAR("L_TRAIN", 12),
        DEF_VAR("L_TRAININT", 15),
        DEF_VAR("L_TSR", 15),
        DEF_VAR("M_ACK", 1),
        DEF_VAR("M_ADHESION", 1),
        DEF_VAR("M_AIRTIGHT", 2),
        DEF_VAR("M_AXLELOADCAT", 7),
        DEF_VAR("M_CURRENT", 10),
        DEF_VAR("M_DUP", 2),
        DEF_VAR("M_ERROR", 8),
        DEF_VAR("M_LEVEL", 3),
        DEF_VAR("M_LEVELTEXTDISPLAY", 3),
        DEF_VAR("M_LEVELTR", 3),
        DEF_VAR("M_LINEGAUGE", 8),
        DEF_VAR("M_LINEAXLELOADCAT", 16),
        DEF_VAR("M_LOADINGGAUGE", 8),
        DEF_VAR("M_LOC", 3),
        DEF_VAR("M_MAMODE", 2),
        DEF_VAR("M_MCOUNT", 8),
        DEF_VAR("M_MODE", 5),
        DEF_VAR("M_MODE", 4), // v1 + v2
        DEF_VAR("M_MODETEXTDISPLAY", 4),
        DEF_VAR("M_NVAVADH", 5),
        DEF_VAR("M_NVCONTACT", 2),
        DEF_VAR("M_NVDERUN", 1),
        DEF_VAR("M_NVEBCL", 4),
        DEF_VAR("M_NVKRINT", 5),
        DEF_VAR("M_NVKTINT", 5),
        DEF_VAR("M_NVKVINT", 7),
        DEF_VAR("M_PLATFORM", 4),
        DEF_VAR("M_POSITION", 24),
        DEF_VAR("M_POSITION", 20), // v1
        DEF_VAR("M_TRACKCOND", 4),
        DEF_VAR("M_VOLTAGE", 4),
        DEF_VAR_CUSTOM("M_VERSION", 7, NULL, NULL, dissect_var_ret_m_version),
        DEF_VAR("N_AXLE", 10),
        DEF_VAR("N_ITER", 5),
        DEF_VAR("N_PIG", 3),
        DEF_VAR("N_TOTAL", 3),
        DEF_VAR("NC_CDDIFF", 4),
        DEF_VAR("NC_CDTRAIN", 4),
        DEF_VAR("NC_DIFF", 4),
        DEF_VAR("NC_TRAIN", 15),
        DEF_VAR("NID_BG", 14),
        DEF_VAR("NID_C", 10),
        DEF_VAR("NID_CTRACTION", 10),
        DEF_VAR("NID_EM", 4),
        DEF_VAR("NID_ENGINE", 24),
        DEF_VAR("NID_LOOP", 14),
        DEF_VAR("NID_LRBG", 24),
        DEF_VAR("NID_LTRBG", 24),
        DEF_VAR("NID_LX", 8),
        DEF_VAR("NID_MESSAGE", 8),
        DEF_VAR("NID_MN", 24),
        DEF_VAR("NID_OPERATIONAL", 32),
        DEF_VAR("NID_PACKET", 8),
        DEF_VAR("NID_PRVLRBG", 24),
        DEF_VAR("NID_RADIO", 64),
        DEF_VAR("NID_RBC", 14),
        DEF_VAR("NID_RIU", 14),
        DEF_VAR("NID_NTC", 8),
        DEF_VAR("NID_TEXTMESSAGE", 8),
        DEF_VAR("NID_TSR", 8),
        DEF_VAR("NID_VBCMK", 6),
        DEF_VAR("NID_XUSER", 9),
        DEF_VAR("Q_ASPECT", 1),
        DEF_VAR("Q_CONFTEXTDISPLAY", 1),
        DEF_VAR("Q_DANGERPOINT", 1),
        DEF_VAR("Q_DIFF", 2),
        DEF_VAR("Q_DESK", 1),
        DEF_VAR("Q_DIR", 2),
        DEF_VAR("Q_DIRLRBG", 2),
        DEF_VAR("Q_DIRTRAIN", 2),
        DEF_VAR("Q_DLRBG", 2),
        DEF_VAR("Q_EMERGENCYSTOP", 2),
        DEF_VAR("Q_ENDTIMER", 1),
        DEF_VAR("Q_FRONT", 1),
        DEF_VAR("Q_GDIR", 1),
        DEF_VAR("Q_INFILL", 1),
        DEF_VAR("Q_INTEGRITY", 2),
        DEF_VAR("Q_SAFECONSISTLENGTH", 1),
        DEF_VAR("Q_LGTLOC", 1),
        DEF_VAR("Q_LINK", 1),
        DEF_VAR("Q_LOCACC", 6),
        DEF_VAR("Q_LINKORIENTATION", 1),
        DEF_VAR("Q_LINKREACTION", 2),
        DEF_VAR("Q_LOOPDIR", 1),
        DEF_VAR("Q_LSSMA", 1),
        DEF_VAR("Q_LXSTATUS", 1),
        DEF_VAR("Q_MAMODE", 1),
        DEF_VAR("Q_MARQSTREASON", 5),
        DEF_VAR("Q_MEDIA", 1),
        DEF_VAR("Q_MPOSITION", 1),
        DEF_VAR("Q_NETWORKTYPE", 2),
        DEF_VAR("Q_NEWCOUNTRY", 1),
        DEF_VAR("Q_NVDRIVER_ADHES", 1),
        DEF_VAR("Q_NVEMRRLS", 1),
        DEF_VAR("Q_NVGUIPERM", 1),
        DEF_VAR("Q_NVINHSMICPERM", 1),
        DEF_VAR("Q_NVKINT", 1),
        DEF_VAR("Q_NVKVINTSET", 2),
        DEF_VAR("Q_NVLOCACC", 6),
        DEF_VAR("Q_NVSBFBPERM", 1),
        DEF_VAR("Q_NVSBTSMPERM", 1),
        DEF_VAR("Q_ORIENTATION", 1),
        DEF_VAR("Q_OVERLAP", 1),
        DEF_VAR("Q_PBDSR", 1),
        DEF_VAR("Q_PLATFORM", 2),
        DEF_VAR("Q_RBC", 1),
        DEF_VAR("Q_RIU", 1),
        DEF_VAR("Q_SCALE", 2),
        DEF_VAR("Q_SECTIONTIMER", 1),
        DEF_VAR("Q_SLEEPSESSION", 1),
        DEF_VAR("Q_SRSTOP", 1),
        DEF_VAR("Q_SSCODE", 4),
        DEF_VAR("Q_STATUSLRBG", 2),
        DEF_VAR("Q_STOPLX", 1),
        DEF_VAR("Q_SUITABILITY", 2),
        DEF_VAR("Q_TEXT", 8),
        DEF_VAR("Q_TEXTCLASS", 2),
        DEF_VAR("Q_TEXTCONFIRM", 2),
        DEF_VAR("Q_TEXTDISPLAY", 1),
        DEF_VAR("Q_TEXTREPORT", 1),
        DEF_VAR("Q_TRACKINIT", 1),
        DEF_VAR("Q_UPDOWN", 1),
        DEF_VAR("Q_VBCO", 1),
        DEF_VAR("T_CYCLOC", 8),
        DEF_VAR("T_CYCRQST", 8),
        DEF_VAR("T_LSSMA", 8),
        DEF_VAR("T_ENDTIMER", 10),
        DEF_VAR("T_EMA", 10),
        DEF_VAR("T_MAR", 8),
        DEF_VAR("T_NVCONTACT", 8),
        DEF_VAR("T_NVOVTRP", 8),
        DEF_VAR("T_OL", 10),
        DEF_VAR("T_SECTIONTIMER", 10),
        DEF_VAR("T_TEXTDISPLAY", 10),
        DEF_VAR("T_TIMEOUTRQST", 10),
        DEF_VAR("T_TRAIN", 32),
        DEF_VAR("T_VBC", 8),
        DEF_VAR("V_AXLELOAD", 7),
        DEF_VAR("V_DIFF", 7),
        DEF_VAR("V_EMA", 7),
        DEF_VAR("V_LX", 7),
        DEF_VAR("V_MAIN", 7),
        DEF_VAR("V_MAMODE", 7),
        DEF_VAR("V_MAXTRAIN", 7),
        DEF_VAR("V_NVALLOWOVTRP", 7),
        DEF_VAR("V_NVKVINT", 7),
        DEF_VAR("V_NVLIMSUPERV", 7),
        DEF_VAR("V_NVONSIGHT", 7),
        DEF_VAR("V_NVSUPOVTRP", 7),
        DEF_VAR("V_NVREL", 7),
        DEF_VAR("V_NVSHUNT", 7),
        DEF_VAR("V_NVSTFF", 7),
        DEF_VAR("V_NVUNFIT", 7),
        DEF_VAR("V_RELEASEDP", 7),
        DEF_VAR("V_RELEASEOL", 7),
        DEF_VAR("V_REVERSE", 7),
        DEF_VAR("V_SM", 7),
        DEF_VAR("V_STATIC", 7),
        DEF_VAR("V_TRAIN", 7),
        DEF_VAR("V_TSR", 7),
        DEF_VAR_CUSTOM("X_TEXT", 8, NULL, NULL, dissect_var_ret_x_text),
        DEF_VAR("M_AXLELOAD", 7), // v1
        DEF_VAR("M_TRACKCONDBC", 4), // v1
        DEF_VAR("M_TRACTION", 8), // v1
        DEF_VAR("Q_TRACKDEL", 1), // v1
};

#define VAR(name) (etcs_variables[ VAR_ ##name ])
